version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: betz_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: betz_user
      POSTGRES_PASSWORD: betz_password
      POSTGRES_DB: betz_db
    ports:
      - "5432:5432"
    volumes:
      - betz_postgres_data:/var/lib/postgresql/data

volumes:
  betz_postgres_data: